### PR TITLE
fix: install using lockfiles

### LINKED ISSUE #8: Install does not use lockfile
When installing in CI, it doesn't seem like the lockfile is being used.  This can lead to inconsistent build results when compared to local builds.

### PR DESCRIPTION
**Pull request by rpd10**
fixes #8 

This will detect yarn vs npm.  If yarn, it will execute `yarn install --frozen-lockfile`.  If npm, it will execute `npm ci`

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -27,8 +27,9 @@ async function run() {
     }
 
     const pkgManager = (await ioUtil.exists("./yarn.lock")) ? "yarn" : "npm";
+    const installCmd = pkgManager === 'yarn' ? 'install --frozen-lockfile' : 'ci'
```
Comment (cmgriffing) [inline index.js:30]: Could you switch these over to double quotes to stay consistent with the line before it?

Comment (rpd10) [reply index.js]: Done

**Comment by cmgriffing** [comment]
Awesome thanks.
